### ISSUE TITLE
Prevent vertical scrolling of main viewport when a dialog is open

### ISSUE THREAD

**Issue by chris-pearce** [fedordead/vanilla-ui#19]
When a dialog is open we should append a state hook e.g. `is-dialog-open` to the `<html>` element which allows for the following CSS to be applied:

``` css
html.is-dialog-open {
  overflow-x: hidden;
}
```

This prevents the main viewport being scrolled up and down when a dialog is open which is standard UX behaviour.
